#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_PIPE_PERCENT = 1,
  anon_sym_DASH_DASH = 2,
  anon_sym_PLUS_PLUS = 3,
  anon_sym_PIPE_EQ = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_identifier = 7,
  aux_sym_integer_literal_token1 = 8,
  aux_sym_integer_literal_token2 = 9,
  anon_sym_DQUOTE = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_any_token1 = 12,
  sym_comment = 13,
  sym_document = 14,
  sym__value = 15,
  sym_token = 16,
  sym_barcen = 17,
  sym_luslus = 18,
  sym_bartis = 19,
  sym_cell = 20,
  sym_integer_literal = 21,
  sym_tape_literal = 22,
  sym_cord_literal = 23,
  sym_any = 24,
  aux_sym_document_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PIPE_PERCENT] = "|%",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PIPE_EQ] = "|=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [aux_sym_integer_literal_token1] = "integer_literal_token1",
  [aux_sym_integer_literal_token2] = "integer_literal_token2",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_any_token1] = "any_token1",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_token] = "token",
  [sym_barcen] = "barcen",
  [sym_luslus] = "luslus",
  [sym_bartis] = "bartis",
  [sym_cell] = "cell",
  [sym_integer_literal] = "integer_literal",
  [sym_tape_literal] = "tape_literal",
  [sym_cord_literal] = "cord_literal",
  [sym_any] = "any",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PIPE_PERCENT] = anon_sym_PIPE_PERCENT,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PIPE_EQ] = anon_sym_PIPE_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [aux_sym_integer_literal_token1] = aux_sym_integer_literal_token1,
  [aux_sym_integer_literal_token2] = aux_sym_integer_literal_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_any_token1] = aux_sym_any_token1,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_token] = sym_token,
  [sym_barcen] = sym_barcen,
  [sym_luslus] = sym_luslus,
  [sym_bartis] = sym_bartis,
  [sym_cell] = sym_cell,
  [sym_integer_literal] = sym_integer_literal,
  [sym_tape_literal] = sym_tape_literal,
  [sym_cord_literal] = sym_cord_literal,
  [sym_any] = sym_any,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PIPE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_integer_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_any_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_token] = {
    .visible = true,
    .named = true,
  },
  [sym_barcen] = {
    .visible = true,
    .named = true,
  },
  [sym_luslus] = {
    .visible = true,
    .named = true,
  },
  [sym_bartis] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_tape_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_cord_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_any] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 6,
  [9] = 4,
  [10] = 5,
  [11] = 6,
  [12] = 4,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 14,
  [17] = 13,
  [18] = 14,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 21,
  [29] = 22,
  [30] = 20,
  [31] = 19,
  [32] = 23,
  [33] = 24,
  [34] = 25,
  [35] = 26,
  [36] = 27,
  [37] = 21,
  [38] = 20,
  [39] = 19,
  [40] = 23,
  [41] = 24,
  [42] = 25,
  [43] = 26,
  [44] = 27,
  [45] = 22,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 46,
  [53] = 53,
  [54] = 49,
  [55] = 47,
  [56] = 48,
  [57] = 53,
  [58] = 51,
  [59] = 51,
  [60] = 46,
  [61] = 53,
  [62] = 48,
  [63] = 50,
  [64] = 64,
  [65] = 47,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 50,
  [70] = 66,
  [71] = 49,
  [72] = 66,
  [73] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(12);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == ']') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PIPE_PERCENT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_integer_literal_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_integer_literal_token2);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_integer_literal_token2);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_integer_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_any_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_any_token1);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_any_token1);
      if (lookahead == '+') ADVANCE(9);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_any_token1);
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 16},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 16},
  [71] = {.lex_state = 16},
  [72] = {.lex_state = 16},
  [73] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PIPE_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PIPE_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_integer_literal_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_any_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(64),
    [sym__value] = STATE(3),
    [sym_token] = STATE(3),
    [sym_barcen] = STATE(22),
    [sym_luslus] = STATE(22),
    [sym_bartis] = STATE(22),
    [sym_cell] = STATE(22),
    [sym_integer_literal] = STATE(22),
    [sym_tape_literal] = STATE(22),
    [sym_cord_literal] = STATE(22),
    [sym_any] = STATE(22),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_PIPE_PERCENT] = ACTIONS(7),
    [anon_sym_PLUS_PLUS] = ACTIONS(9),
    [anon_sym_PIPE_EQ] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_integer_literal_token1] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_any_token1] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__value] = STATE(2),
    [sym_token] = STATE(2),
    [sym_barcen] = STATE(22),
    [sym_luslus] = STATE(22),
    [sym_bartis] = STATE(22),
    [sym_cell] = STATE(22),
    [sym_integer_literal] = STATE(22),
    [sym_tape_literal] = STATE(22),
    [sym_cord_literal] = STATE(22),
    [sym_any] = STATE(22),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_PIPE_PERCENT] = ACTIONS(25),
    [anon_sym_PLUS_PLUS] = ACTIONS(28),
    [anon_sym_PIPE_EQ] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(34),
    [aux_sym_integer_literal_token1] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [aux_sym_any_token1] = ACTIONS(46),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__value] = STATE(2),
    [sym_token] = STATE(2),
    [sym_barcen] = STATE(22),
    [sym_luslus] = STATE(22),
    [sym_bartis] = STATE(22),
    [sym_cell] = STATE(22),
    [sym_integer_literal] = STATE(22),
    [sym_tape_literal] = STATE(22),
    [sym_cord_literal] = STATE(22),
    [sym_any] = STATE(22),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_PIPE_PERCENT] = ACTIONS(7),
    [anon_sym_PLUS_PLUS] = ACTIONS(9),
    [anon_sym_PIPE_EQ] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_integer_literal_token1] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_any_token1] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_token] = STATE(62),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_token] = STATE(59),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_token] = STATE(16),
    [sym_barcen] = STATE(29),
    [sym_luslus] = STATE(29),
    [sym_bartis] = STATE(29),
    [sym_cell] = STATE(29),
    [sym_integer_literal] = STATE(29),
    [sym_tape_literal] = STATE(29),
    [sym_cord_literal] = STATE(29),
    [sym_any] = STATE(29),
    [anon_sym_PIPE_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(73),
    [aux_sym_integer_literal_token1] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [aux_sym_any_token1] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_token] = STATE(58),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [8] = {
    [sym_token] = STATE(14),
    [sym_barcen] = STATE(29),
    [sym_luslus] = STATE(29),
    [sym_bartis] = STATE(29),
    [sym_cell] = STATE(29),
    [sym_integer_literal] = STATE(29),
    [sym_tape_literal] = STATE(29),
    [sym_cord_literal] = STATE(29),
    [sym_any] = STATE(29),
    [anon_sym_PIPE_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(73),
    [aux_sym_integer_literal_token1] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [aux_sym_any_token1] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [9] = {
    [sym_token] = STATE(56),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [10] = {
    [sym_token] = STATE(51),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [11] = {
    [sym_token] = STATE(18),
    [sym_barcen] = STATE(29),
    [sym_luslus] = STATE(29),
    [sym_bartis] = STATE(29),
    [sym_cell] = STATE(29),
    [sym_integer_literal] = STATE(29),
    [sym_tape_literal] = STATE(29),
    [sym_cord_literal] = STATE(29),
    [sym_any] = STATE(29),
    [anon_sym_PIPE_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(73),
    [aux_sym_integer_literal_token1] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [aux_sym_any_token1] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [12] = {
    [sym_token] = STATE(48),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [13] = {
    [sym_token] = STATE(40),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [14] = {
    [sym_token] = STATE(33),
    [sym_barcen] = STATE(29),
    [sym_luslus] = STATE(29),
    [sym_bartis] = STATE(29),
    [sym_cell] = STATE(29),
    [sym_integer_literal] = STATE(29),
    [sym_tape_literal] = STATE(29),
    [sym_cord_literal] = STATE(29),
    [sym_any] = STATE(29),
    [anon_sym_PIPE_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(73),
    [aux_sym_integer_literal_token1] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [aux_sym_any_token1] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [15] = {
    [sym_token] = STATE(23),
    [sym_barcen] = STATE(22),
    [sym_luslus] = STATE(22),
    [sym_bartis] = STATE(22),
    [sym_cell] = STATE(22),
    [sym_integer_literal] = STATE(22),
    [sym_tape_literal] = STATE(22),
    [sym_cord_literal] = STATE(22),
    [sym_any] = STATE(22),
    [anon_sym_PIPE_PERCENT] = ACTIONS(7),
    [anon_sym_PLUS_PLUS] = ACTIONS(9),
    [anon_sym_PIPE_EQ] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_integer_literal_token1] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_any_token1] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [16] = {
    [sym_token] = STATE(24),
    [sym_barcen] = STATE(22),
    [sym_luslus] = STATE(22),
    [sym_bartis] = STATE(22),
    [sym_cell] = STATE(22),
    [sym_integer_literal] = STATE(22),
    [sym_tape_literal] = STATE(22),
    [sym_cord_literal] = STATE(22),
    [sym_any] = STATE(22),
    [anon_sym_PIPE_PERCENT] = ACTIONS(7),
    [anon_sym_PLUS_PLUS] = ACTIONS(9),
    [anon_sym_PIPE_EQ] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [aux_sym_integer_literal_token1] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_any_token1] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [17] = {
    [sym_token] = STATE(32),
    [sym_barcen] = STATE(29),
    [sym_luslus] = STATE(29),
    [sym_bartis] = STATE(29),
    [sym_cell] = STATE(29),
    [sym_integer_literal] = STATE(29),
    [sym_tape_literal] = STATE(29),
    [sym_cord_literal] = STATE(29),
    [sym_any] = STATE(29),
    [anon_sym_PIPE_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(73),
    [aux_sym_integer_literal_token1] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [aux_sym_any_token1] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [18] = {
    [sym_token] = STATE(41),
    [sym_barcen] = STATE(45),
    [sym_luslus] = STATE(45),
    [sym_bartis] = STATE(45),
    [sym_cell] = STATE(45),
    [sym_integer_literal] = STATE(45),
    [sym_tape_literal] = STATE(45),
    [sym_cord_literal] = STATE(45),
    [sym_any] = STATE(45),
    [anon_sym_PIPE_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(57),
    [aux_sym_integer_literal_token1] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [aux_sym_any_token1] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_any_token1,
    ACTIONS(83), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [17] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      aux_sym_any_token1,
    ACTIONS(87), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [34] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_any_token1,
    ACTIONS(91), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [51] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_any_token1,
    ACTIONS(95), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [68] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_any_token1,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [85] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      aux_sym_any_token1,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      aux_sym_any_token1,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [119] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_any_token1,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [136] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_any_token1,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [153] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_any_token1,
    ACTIONS(91), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [169] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_any_token1,
    ACTIONS(95), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      aux_sym_any_token1,
    ACTIONS(87), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [201] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_any_token1,
    ACTIONS(83), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [217] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_any_token1,
    ACTIONS(99), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [233] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      aux_sym_any_token1,
    ACTIONS(103), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      aux_sym_any_token1,
    ACTIONS(107), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [265] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_any_token1,
    ACTIONS(111), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_any_token1,
    ACTIONS(115), 7,
      anon_sym_PIPE_PERCENT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_EQ,
      anon_sym_LBRACK,
      aux_sym_integer_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [297] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [345] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_DASH_DASH,
      anon_sym_RBRACK,
  [369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_DQUOTE,
  [376] = 2,
    ACTIONS(121), 1,
      aux_sym_integer_literal_token2,
    ACTIONS(123), 1,
      sym_comment,
  [383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_DASH_DASH,
  [390] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(127), 1,
      aux_sym_integer_literal_token2,
  [397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
  [404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
  [411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
  [418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_SQUOTE,
  [425] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(137), 1,
      aux_sym_integer_literal_token2,
  [432] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_integer_literal_token2,
  [439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DASH_DASH,
  [446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
  [453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_RBRACK,
  [460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACK,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
  [474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_SQUOTE,
  [481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_DASH_DASH,
  [488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
  [495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
  [502] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_integer_literal_token2,
  [509] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(161), 1,
      aux_sym_integer_literal_token2,
  [516] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_integer_literal_token2,
  [523] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(165), 1,
      aux_sym_integer_literal_token2,
  [530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
  [537] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(169), 1,
      aux_sym_integer_literal_token2,
  [544] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_integer_literal_token2,
  [551] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(173), 1,
      aux_sym_integer_literal_token2,
  [558] = 2,
    ACTIONS(123), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_integer_literal_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 17,
  [SMALL_STATE(21)] = 34,
  [SMALL_STATE(22)] = 51,
  [SMALL_STATE(23)] = 68,
  [SMALL_STATE(24)] = 85,
  [SMALL_STATE(25)] = 102,
  [SMALL_STATE(26)] = 119,
  [SMALL_STATE(27)] = 136,
  [SMALL_STATE(28)] = 153,
  [SMALL_STATE(29)] = 169,
  [SMALL_STATE(30)] = 185,
  [SMALL_STATE(31)] = 201,
  [SMALL_STATE(32)] = 217,
  [SMALL_STATE(33)] = 233,
  [SMALL_STATE(34)] = 249,
  [SMALL_STATE(35)] = 265,
  [SMALL_STATE(36)] = 281,
  [SMALL_STATE(37)] = 297,
  [SMALL_STATE(38)] = 305,
  [SMALL_STATE(39)] = 313,
  [SMALL_STATE(40)] = 321,
  [SMALL_STATE(41)] = 329,
  [SMALL_STATE(42)] = 337,
  [SMALL_STATE(43)] = 345,
  [SMALL_STATE(44)] = 353,
  [SMALL_STATE(45)] = 361,
  [SMALL_STATE(46)] = 369,
  [SMALL_STATE(47)] = 376,
  [SMALL_STATE(48)] = 383,
  [SMALL_STATE(49)] = 390,
  [SMALL_STATE(50)] = 397,
  [SMALL_STATE(51)] = 404,
  [SMALL_STATE(52)] = 411,
  [SMALL_STATE(53)] = 418,
  [SMALL_STATE(54)] = 425,
  [SMALL_STATE(55)] = 432,
  [SMALL_STATE(56)] = 439,
  [SMALL_STATE(57)] = 446,
  [SMALL_STATE(58)] = 453,
  [SMALL_STATE(59)] = 460,
  [SMALL_STATE(60)] = 467,
  [SMALL_STATE(61)] = 474,
  [SMALL_STATE(62)] = 481,
  [SMALL_STATE(63)] = 488,
  [SMALL_STATE(64)] = 495,
  [SMALL_STATE(65)] = 502,
  [SMALL_STATE(66)] = 509,
  [SMALL_STATE(67)] = 516,
  [SMALL_STATE(68)] = 523,
  [SMALL_STATE(69)] = 530,
  [SMALL_STATE(70)] = 537,
  [SMALL_STATE(71)] = 544,
  [SMALL_STATE(72)] = 551,
  [SMALL_STATE(73)] = 558,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(50),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(71),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(70),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(68),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(65),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_barcen, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_barcen, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_literal, 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_literal, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_luslus, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_luslus, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bartis, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bartis, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape_literal, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tape_literal, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cord_literal, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cord_literal, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_YOUR_LANGUAGE_NAME(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
